// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationItem: typeof import('./src/components/ApplicationItem/index.vue')['default']
    Avatar: typeof import('./src/components/Avatar/index.vue')['default']
    CardDescItem: typeof import('./src/components/CardDescItem/index.vue')['default']
    CheckedFooter: typeof import('./src/components/CheckedFooter/index.vue')['default']
    CommonEmpty: typeof import('./src/components/CommonEmpty/index.vue')['default']
    CustomEdit: typeof import('./src/components/CustomEdit/index.vue')['default']
    DetailInfoItem: typeof import('./src/components/DetailInfoItem/index.vue')['default']
    GenericListItem: typeof import('./src/components/GenericListItem/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingRowItem: typeof import('./src/components/SettingRowItem/index.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopover: typeof import('vant/es')['Popover']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VideoPlayer: typeof import('./src/components/VideoPlayer/index.vue')['default']
  }
}
